# Stylish-haskell configuration file
#
# See `stylish-haskell --defaults` or
# https://github.com/jaspervdj/stylish-haskell/blob/master/data/stylish-haskell.yaml
# for usage.

steps:
  - simple_align:
      cases: false
      top_level_patterns: false
      records: false
  - imports:
      align: none
      list_align: with_alias
      pad_module_names: false
      long_list_align: new_line_multiline
      empty_list_align: inherit
      list_padding: 4
      separate_lists: true
      space_surround: false
  - language_pragmas:
      style: vertical
      align: false
      remove_redundant: true
  - trailing_whitespace: {}

columns: 120
newline: native
language_extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - ExistentialQuantification
  - ExplicitNamespaces
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - MultiParamTypeClasses
  - NamedFieldPuns
  - PackageImports
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
